### ISSUE TITLE
Issues Encountered When Running starter_code.py  

### ISSUE THREAD

**Issue by liang-hongtao** [UMass-Foundation-Model/HAZARD#1]
I am encountering some issues when trying to run the starter_code.py file. I am using the `submit` function in my code as follows:  

python from HAZARD import submit  submit(output_dir="outputs/", env_name="fire", agent="mcts", port=10826, max_test_episode=1,)        # perceptional: bool = False,  # turn on this for the perceptional version of HAZARD        #  effect_on_agents: bool = False,  # turn on this to let hazard affect agents        #  run_on_test: bool = False,  # turn off to run on test set 

When I run this code, I receive a prompt stating that I need to launch my own build. I am unsure what this prompt means and how to resolve this issue. I have tried creating a new Anaconda environment and installing all dependencies in that environment, but the issue persists.  I would appreciate any help on how to resolve this issue. Thank you!
![Uploading QQ截图20240226223703.jpg…]()

**Comment by zhouqqhh** [comment]
Hi Hongtao,

I can not open your attached image. But according to your text, I believe you need to run both the python code and launch a ThreeDWorld Build on your server in parallel. Please refer to the document of ThreeDWorld (https://github.com/threedworld-mit/tdw/blob/master/Documentation/lessons/setup/server.md) for how to launch a Build.

Here I provide an example:
First, install ThreeDWorld and launch a Xorg process. Download ThreeDWorld Build from https://github.com/threedworld-mit/tdw/releases, which will include `TDW.x86_64`.
Then, after running `python <your_code>.py`, start another tmux window and run
`DISPLAY=:X.0 ./TDW.x86_64 -port=<same port as in your python code>` (the DISPLAY variable should match your Xorg config)

**Comment by liang-hongtao** [comment]
I appreciate your prompt response to my previous inquiry regarding the issues I encountered while running the  file.

However, I am facing a bit of confusion in implementing your suggested solution. I am currently testing the code on my personal PC, and I noticed that the provided guidance involves launching a ThreeDWorld Build on a server. My understanding is that this might not be applicable to my local testing setup.

When attempting to run the code on my PC, I receive the message "You need to launch your own build." I followed your advice to install ThreeDWorld, but I did not encounter the need to initiate an Xorg process on my local machine.

Could you kindly provide further clarification or alternative steps that I can take to address this issue while testing the code locally on my personal PC? Your assistance is highly valued, and I am eager to resolve this matter to proceed with my work.

The log entry in the terminal is as follows:
PS G:\tdw\HAZARD>  & 'd:\software\anaconda\envs\pytorch38\python.exe' 'c:\Users\Administrator\.vscode\extensions\ms-python.debugpy-2024.0.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher' '54465' '--' 'g:\tdw\HAZARD\starter_code.py'
d:\software\anaconda\envs\pytorch38\lib\site-packages\gym\envs\registration.py:498: UserWarning: WARN: Overriding environment flood-v0 already in registry.
  logger.warn(f"Overriding environment {new_spec.id} already in registry.")
d:\software\anaconda\envs\pytorch38\lib\site-packages\gym\envs\registration.py:498: UserWarning: WARN: Overriding environment fire-v0 already in registry.
  logger.warn(f"Overriding environment {new_spec.id} already in registry.")
2024-02-27 15:16:20,043 - fire_mcts_02/27/2024, 15:16:20 - INFO - Environment Createdreated
2024-02-27 15:16:20,043 - fire_mcts_02/27/2024, 15:16:20 - INFO - done
outputs/mm_craftroom_2a-1
OUTPUT_DIR outputs/mm_craftroom_2a-1
2024-02-27 15:16:20,044 - fire_mcts_02/27/2024, 15:16:20 - INFO - Episode: 1/1 ironment ... data is G:\tdw\HAZARD\src\HAZARD\data\room_setup_fire\mm_craftroom_2a-1
2024-02-27 15:16:20,045 - fire_mcts_02/27/2024, 15:16:20 - INFO - Resetting Environment ... data is G:\tdw\HAZARD\src\HAZARD\data\room_setup_fire\mm_craftroom_2a-1
You need to launch your own build.

Thank you for your understanding and support.

**Comment by zhouqqhh** [comment]
Sorry, I just supposed you are running on a remote server. If you run it on your PC, you can run the TDW executable file in parallel with your python code, and then the python controller will connect to the TDW process.
The executable file is included in the TDW Build package at https://github.com/threedworld-mit/tdw/releases. You can choose the package that match your PC's system. Taking Windows as an example, you can download `TDW_Windows.zip`, and execute `TDW.exe` in parallel with your python code.
For more details about how to run ThreeDWorld, please refer to https://github.com/threedworld-mit/tdw/blob/master/Documentation/lessons/setup/install.md

**Comment by liang-hongtao** [comment]
Sorry to bother you again, I followed your instructions and downloaded tdw_windows.zip and ran TDW.exe, but when I run starter_code.py I face the same problem, it tells me `You need to launch your own build. ` in the file `src\HAZARD\envs\fire\fire.py`. At the same time, I configured the same environment on my Ubuntu system, but also encountered the same problem (see the attached image).

![20240229193740](https://github.com/UMass-Foundation-Model/HAZARD/assets/99383082/b6413aef-8aa3-4fd8-ac5b-b46594eb925b)

After debugging the code line by line, I found that in the 54th line of the code `super(). __init__(port, check_version, launch_build)`, this error occurs. The stack call information is shown below.

![20240229220142](https://github.com/UMass-Foundation-Model/HAZARD/assets/99383082/74a31725-8631-44b9-b075-35fac3cb237f)

May I ask if there was a mistake in my operation, or how should I solve this problem? Thank you for your answer.

**Comment by zhouqqhh** [comment]
You need to make sure the port of TDW build is the same as the port in `starter_code.py`. The default port used by TDW build is 1071, so please either change the port in `starter_code.py` to 1071, or add `-port=XXX` parameter when running TDW build file.

**Comment by liang-hongtao** [comment]
Big thanks to you for swiftly resolving my issue!
