### ISSUE TITLE
Issue with Replicating Reinforcement Learning Agent

### ISSUE THREAD

**Issue by liang-hongtao** [UMass-Foundation-Model/HAZARD#2]
I am attempting to replicate the reinforcement learning agent, but I am encountering several issues. Specifically, in the `rl.py` file, lines 13-15 reference certain `.pt` files that are not available on the GitHub page. Consequently, I assume I need to train these files on my own.

Firstly, I am uncertain whether I should use the code under the ppo directory for training the agent. After following the installation instructions in the readme.md file under the ppo directory, I couldn't locate the train.py file. When attempting to execute the main_fire.py file, the system indicates errors in lines 8-10 related to the imports of `envs.fire` `envs.wind` and `envs.flood` After commenting out these lines and running the script, I encountered an error on line 96, specifically at `obs = envs.reset()`.

Additionally, the system notifies me that there is no model for firev0 in the Gym. I am unsure whether there is an issue with my Gym installation or if I have made an error in my other actions.

Steps Taken:

Attempted training RL agent using the ppo directory.
Followed installation instructions in the readme.md file under the ppo directory.
Unable to find the train.py file after installation.
Attempted running `main_fire.py` with commented out lines 8-10, resulting in an error at line 96 (`obs = envs.reset()`).
Received a notification about the absence of the `firev0` model in Gym.
Request for Assistance:

I seek guidance on the following issues:

Clarification on whether the ppo directory is suitable for training the agent.
Assistance with locating the missing train.py file.
Resolution for errors encountered when running main_fire.py.
Guidance on the reported absence of the `firev0`,`floodv0`, and `windv0` model in Gym.
Your help in resolving these matters would be greatly appreciated. Thank you.

**Comment by zhouqqhh** [comment]
Hi, we have seen your issue. RL agent has a separated code framework from other types of agents and we are currently trying to fix this soon.

**Comment by EEEEEericKKK** [comment]
Hi, sorry for the inconvenience. When we organize our code, some paths changed and so did import behavior. We have updated our code and documentation. Feel free to contact us if you encounter further problems.
