### ISSUE TITLE
Wind environment

### ISSUE THREAD

**Issue by grig-guz** [UMass-Foundation-Model/HAZARD#3]
Hi, does the wind environment work on the last main branch commit? I had quite a few import errors, but after fixing those I am still left with:

``` 
File "/Users/grigoriiguz/projects/HAZARD/src/HAZARD/envs/wind/object.py", line 5, in ObjectStatus 
def __init__(self, idx, constants: Constants=default_const, 
NameError: name 'default_const' is not defined
```

**Comment by zhouqqhh** [comment]
Hi Grig, sorry for this bug. It seems that we falsely deleted some import lines when converting the repo to a pip package. We will fix it and push soon.

**Comment by zhouqqhh** [comment]
Hi, we just fixed this bug and wind environment on the latest main branch works now!
